import useSWR from "swr";
import Head from "next/head";

const fetcher = (url) => fetch(url).then((r) => r.json());

export default function Home() {
  const { data, error } = useSWR("https://json-host.herokuapp.com/db", fetcher);
  if (error) return <div>failed to load</div>;
  if (!data) return <div>loading...</div>;
  return (
    <div>
      <Head>
        <title>Loading JSON Data with SWR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Example for loading a static json file using SWR</h1>
        <h2>Instructions</h2>
        <ul>
          <li>Place the json file inside the public folder</li>
          <li>Use SWR to load the file from /randomuser.json</li>
        </ul>
        <h3>Loaded Data</h3>
        <p>
          Name: {data.results[0].name.first} {data.results[0].name.last}
        </p>
      </div>
    </div>
  );
}
