import useSWR from "swr";
import Head from "next/head";

const fetcher = (url) => fetch(url).then((r) => r.json());

export default function Home() {
  const { data, error } = useSWR("https://json-host.herokuapp.com/db", fetcher);
  if (error) return <div>failed to load</div>;
  if (!data) return <div>loading...</div>;
  return (
    <div>
      <Head>
        <title>Loading JSON Data with SWR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Example for loading external json file using SWR</h1>
        <h2>Instructions</h2>
        <ul>
          <li>Host your json data file on an external server like S3 or heroku</li>
          <li>Use SWR to load the file</li>
        </ul>
        <h3>Loaded from https://json-host.herokuapp.com/db</h3>
        <p>
          ID: {data.data.id} {data.data.uid}
        </p>
      </div>
    </div>
  );
}
